### ISSUE TITLE
 MISA-MD v0.5.0 roadmap

### ISSUE THREAD

**Issue by genshen** [misa-md/MISA-MD#2]
## MISA-MD v0.5.0 roadmap
- [x] CUDA/HIP interface to create pin memory
- [x] Support any types of alloy
- [x] restart simulation from a system status dumping file
- [ ] (Experimental) DL potential
- [ ] Potential: system potential
- [ ] Tests: more unit tests
- [ ] More LAMMPS compare
- [ ] IO: dump step offset, limit, dump double current time.
- [ ] IO: file should be closed after all finished.
- [ ] IO: write atom number
- [x] IO: select to dump position/velocity/force 
- [x] IO: use different dump in one stage
- [x] AoS (array of struct) and SoA (struct of array) atoms data struct support
- [ ] More ...
